---
- name: Create volume partition
  parted:
    device: /dev/sdb
    number: 1

- name: Create a volume group
  lvg:
    vg: vg_database
    state: present
    pvs: /dev/sdb

- name: Create /dev/sdb partition
  lvol:
    vg: vg_database
    lv: lv_mysql
    size: '800'
    active: true
    force: true

- name: Create filesystem partition
  filesystem:
    fstype: xfs
    dev: /dev/mapper/vg_database-lv_mysql

- name: Mount lv_mysql volume
  mount:
    path: /mnt/mysql_backups
    src: /dev/mapper/vg_database-lv_mysql
    opts: rw
    fstype: xfs
    state: mounted

- name: Install mysql package
  package:
    name: mysql-community-server
    state: latest

- name: Start firewalld service
  service:
    name: firewalld
    state: started
    enabled: true

- name: Open mysql connections firewall
  firewalld:
    state: enabled
    permanent: yes
    port: 3306/tcp
    immediate: yes

- name: Install python pip
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python-pip
    - MySQL-python

- name: Enable MySQL service
  service:
    name: mysqld
    state: started
    enabled: true

- name: Set MySQL user password
  mysql_user:
    name: root
    login_user: root
    login_password: ""
    password: "{{ database_password }}"

- name: Override my.cnf
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    mode: '0644'
