# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # ---------------------------------
  # ansible-control.hl.local
  # ---------------------------------
  config.vbguest.auto_update = false
  config.vm.define "ansible-control.hl.local" do |ansible_control|
    ansible_control.vagrant.plugins = { "vagrant-vbguest" => { "version" => "1.0.0" } }
    ansible_control.vm.box = "centos/7"
    ansible_control.vm.hostname = "ansible-control.hl.local"
    ansible_control.vm.network "private_network", ip: "172.16.10.11"
    ansible_control.vm.provision "file", source: "ssh-keys/ansible_exam", destination: "/home/vagrant/.ssh/ansible_exam"
    ansible_control.vm.provision "shell", inline: <<-SHELL
      sudo yum -y install epel-release
      sudo yum -y install ansible
      sudo yum -y install lvm2
    SHELL
    ansible_control.vm.provision "shell", inline: <<-SHELL
      echo "Host *" > /home/vagrant/.ssh/config
      echo "StrictHostKeyChecking no" >> /home/vagrant/.ssh/config
      for i in {12..15}; do ANSIBLE_HOST_KEY_CHECKING=false ansible -c ssh --private-key /home/vagrant/.ssh/ansible_exam -i "172.16.10.${i}," -u vagrant -m ping all; done;
    SHELL
    ansible_control.vm.synced_folder "plays", "/home/vagrant/plays"
    ansible_control.vm.provider :virtualbox do |vb|
      vb.name = "ansible-control.hl.local"
    end
  end

end
