---
- name: managed nodes
  hosts: all
  become: true

  tasks:
    - name: create automation user
      user:
        name: automation
        password: "{{ 'devops' | password_hash('sha256') }}"

    - name: add automation user as sudoer
      lineinfile:
        path: /etc/sudoers
        state: present
        line: 'automation ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s

